apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datadog-agent
  name: datadog-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datadog-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: datadog-agent
    spec:
      containers:
        - env:
            - name: DD_AC_EXCLUDE
              value: name:datadog-agent
            - name: DD_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: DD_API_KEY
                  name: sandbox-docker-env
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_LOGS_ENABLED
              value: "TRUE"
            - name: DD_LOG_LEVEL
              value: TRACE
            - name: DD_SITE
              valueFrom:
                configMapKeyRef:
                  key: DD_SITE
                  name: sandbox-docker-env
          image: datadog/agent:latest
          name: datadog-agent
          ports:
            - containerPort: 8126
              protocol: TCP
            - containerPort: 8125
              protocol: UDP
          volumeMounts:
            - mountPath: /host/proc
              name: datadog-agent-claim1
              readOnly: true
            - mountPath: /host/sys/fs/cgroup
              name: datadog-agent-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: datadog-agent-claim1
          persistentVolumeClaim:
            claimName: datadog-agent-claim1
            readOnly: true
        - name: datadog-agent-claim2
          persistentVolumeClaim:
            claimName: datadog-agent-claim2
            readOnly: true
