apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - env:
            - name: DD_AGENT_HOST
              value: datadog-agent
            - name: DD_DATA_STREAMS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "1"
            - name: DD_SERVICE
              value: producer
            - name: DD_TRACE_DEBUG
              value: "1"
            - name: KAFKA_BROKER
              value: kafka:9092
          image: producer
          name: producer
      restartPolicy: Always
