apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: marvel-python-backend
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        ad.datadoghq.com/postgres.checks: |
          {
            "postgresql": {
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "5432",
                  "username": "datadog",
                  "password":"securepassword",
                  "dbm": "true"
                }
              ]
            }
          }  
    spec:
      containers:
      - name: postgres
        image: postgres:13
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "securepassword"
        - name: POSTGRES_DB
          value: "userdb"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
          subPath: pgdata
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
